version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "sample-react-counter-main"
    AWS_REGION: "us-east-1"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 777513753288.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPOSITORY_URI=777513753288.dkr.ecr.us-east-1.amazonaws.com/sample-react-counter-main
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Repo URI: $777513753288.dkr.ecr.us-east-1.amazonaws.com/sample-react-counter-main"
      - echo "Image Tag: $IMAGE_TAG"

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing image definitions file..."
      - printf '[{"name":"react-counter-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "Build completed on $(date)"

artifacts:
  files:
    - imagedefinitions.json
